apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  role: KarpenterNodeRole
  subnetSelectorTerms:
    - id: subnet-02aeb36b1eea04b17
    - id: subnet-03ff18f97661f3125
  securityGroupSelectorTerms:
    - id: sg-0a641298d83bf5fb3
  tags:
    managed-by: karpenter
    provisioned-by: argocd
