# apps/karpenter/nodeclass.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"    # AFTER karpenter controller is up
spec:
  project: default
  source:
    repoURL: https://github.com/pradeep101010/argo-cd-automation.git
    targetRevision: main
    path: apps/karpenter/config          # folder with nodeclass + nodepool yamls
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true                     # if someone kubectl edits nodepool → auto reverted